#!/bin/bash
( sleep 1; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)
( sleep 1 ; /usr/bin/wget --no-check-certificate -O /dev/null https://winimi.de/run_bid_agent/ >> /home/winimdb9/www.winimi.de/live/storage/logs/winimi-imp-cron.log)

